### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by scalopus** [omise/omise-php#27]
Any purpose about why the library is not using namespace?

**Comment by robinclart** [comment]
Since we don't have any control over which version of PHP the library is gonna be run and we had some customer on version older than 5.3 we decided not to use namespaces.

**Comment by scalopus** [comment]
Are you not like to have a separate branch for EOL PHP? I think developer would love for have some language features that you be able to make a library look pretty. There are some several things that just coming up in recent years to improve the quality of code. ex. PSR standard.

At least, I think to support a library where the dependencies (such the PHP itself) are all obsoleted would risk to a system and a library itself. When step up the new major version of library, it may be a good time to arrange the code to be more practical.

**Comment by robinclart** [comment]
I'm a practical guy. Doing two versions isn't practical at the moment. Neither for us, nor for our users. This is Thailand, don't underestimate what is still running out there. I'm not saying we won't do it but instead that right now isn't the time.

We're still adding feature quite often and implementing new features twice isn't something I can dedicate time to. We love backward compatibility and being nice to our users, and we hate sunsets and forcing people to put up with the chore of updating just because: pretty.

Giving two separate documentation, with two different way of installing things is confusing. Confused people will in turn contact our support and I'd prefer not have our support spend too much time on those kind of thing if I can help it. Furthermore if we decide to EOL the old way (simple class) we then force users to upgrade their infrastructure if they want the new features because of a choice I made for them. And I'm sure they have better things to do.

I'm happy to debate this further with you but as far as I'm concerned I'm not gonna implement namespace right now just for the sake of perceived "prettiness".

**Comment by scalopus** [comment]
Ahhh..... OK. Thank you for give a detail. :dancer: :beers:
Have fun Friday.

**Comment by robinclart** [comment]
You're welcome. If you have anything else you want to ask. We're always happy to help.
