### ISSUE TITLE
update prerequisities install php 5.3 eol

### ISSUE THREAD

**Issue by EvertonMelo** [omise/omise-php#74]
according to the official website of the php project.

5.3 	after: 3 years, 6 months ago 	enf of life .
5.3.29 ( 2017 )

font: http://php.net/eol.php

we need to do a source code update for the supported versions.

Branch | Initial Release | Active Support Until | Security Support Until

php 5.6 or 7.0; 7.1 and 7.2 
http://php.net/supported-versions.php

without it the site is vulnerable to dozens of CVEs:

font: https://www.securityfocus.com/bid/41991

**Comment by EvertonMelo** [comment]
Okay, you're not interested.

**Comment by guzzilar** [comment]
@EvertonMelo Hi,
Apologise for my silent, I agreed that we should review and do source code update once to prevent any security vulnerable issues that had happened on PHP below v5.6. 

However, this might be a tough and long task to achieve regarding that many servers in the website market still provide PHP around version 5.4 ~ 5.5 for users. 
The fastest action that I think I'll take right now is to mention on our README and all docs that we are not recommend to use Omise-PHP with PHP version below v5.6 due to the end of life cycle that you mentioned above.

If you have any ideas please feel free to submit either pull request or issue ticket.
It might take time to response (sorry) but we would definitely love to hear our folks' opinions.

And, thanks for this report.
Nam.
